version: '2.2'
services:
  mongo:
    image: mongo:3.4
    networks:
      - unifi
    restart: always
    volumes:
      - db:/data/db
  controller:
    image: "jacobalberty/unifi:${TAG:-latest}"
    depends_on:
      - mongo
    init: true
    networks:
      management:
        ipv4_address: 192.168.10.2
      home:
        ipv4_address: 192.168.3.2
      unifi:
    restart: always
    volumes:
      - data:/unifi/data
      - log:/unifi/log
      - cert:/unifi/cert
      - init:/unifi/init.d
    environment:
      DB_URI: mongodb://mongo/unifi
      STATDB_URI: mongodb://mongo/unifi_stat
      DB_NAME: unifi
      RUNAS_UID0: $RUNAS_UID0
      TZ: $TZ
      UNIFI_UID: $UNIFI_UID
      UNIFI_GID: $UNIFI_GID
    ports:
      - "8080:8080"
      - "8443:8443"
      - "3478:3478/udp"
      - "10001:10001/udp"
  logs:
    image: bash
    depends_on:
      - controller
    command: bash -c 'tail -f /unifi/log/*'
    restart: always
    volumes:
      - log:/unifi/log

volumes:
  db:
  data:
  log:
  cert:
  init:

networks:
  unifi:
  management:
    driver: macvlan
    driver_opts:
      parent: enp1s0.10 
    ipam:
      config:    
      - subnet: 192.168.10.0/24
  home:
    driver: macvlan
    driver_opts:
      parent: enp1s0
    ipam:
      config:
      - subnet: 192.168.3.0/24
        gateway: 192.168.3.1






